version: 2
jobs:
  deploy-prod:
    docker:
      - image: circleci/node
    environment: 
      GOOGLE_MAPS_API: $GOOGLE_MAPS_API
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      
    steps:
      - checkout
      - run:
          command: |
            npm i && npm run build
            pwd
            ls
            scp -oStrictHostKeyChecking=no -r /home/circleci/project/.next/* $DROPLET_USER@$DROPLET_IP:/home/circleci/conf-hub/.next/
            pm2 start --name "conf-hub" npm -- start

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy-prod:
          filters:
            branches:
              only:
                - master
